### ISSUE TITLE
Flask 0.7.2 not allowing GoogleMaps to init

### ISSUE THREAD

**Issue by jharia** [rochacbruno/Flask-GoogleMaps#7]
I'm on Flask 0.7.2, and when I try to import 'flask-googlemaps' and add 'GoogleMaps(app)' , I receive a SIGTERM with the following error message:

'''
(env)macs-MacBook-Pro:facebook-template-python mac$ foreman start
03:17:33 web.1  | started with pid 2212
03:17:33 web.1  | Traceback (most recent call last):
03:17:33 web.1  |   File "exampleapp.py", line 158, in <module>
03:17:33 web.1  |     GoogleMaps(app)
03:17:33 web.1  |   File "/Users/mac/Dropbox/development/facebook-template-python/env/lib/python2.7/site-packages/flask_googlemaps/__init__.py", line 57, in __init__
03:17:33 web.1  |     self.init_app(app)
03:17:33 web.1  |   File "/Users/mac/Dropbox/development/facebook-template-python/env/lib/python2.7/site-packages/flask_googlemaps/__init__.py", line 62, in init_app
03:17:33 web.1  |     app.add_template_filter(googlemap_html)
03:17:33 web.1  | AttributeError: 'Flask' object has no attribute 'add_template_filter'
03:17:33 web.1  | exited with code 1
03:17:33 system | sending SIGTERM to all processes
SIGTERM received
'''

**Comment by rochacbruno** [comment]
Only works in Flask 0.10
